### ISSUE TITLE
Cannot read property 'contentRect' of null

### ISSUE THREAD

**Issue by gorkamolero** [envato/react-resize-observer-hook#6]
Important bug. Anywhere I try this, this happens. Probably not assigning the ref?

Leaving a Sandbox

https://codesandbox.io/s/unruffled-cdn-y1ywc?file=/src/App.js

**Comment by mdingena** [comment]
When you mount a component that uses `useResizeObserver`, it is going to render its HTML for the first time. The `ResizeObserver` will start observing the element, but meanwhile `useResizeObserver` has no size information yet (during the first render cycle of the component). Its internal `observedEntry` is initialised to `null` which is what will be returned.

The `ResizeObserver` now sees the rendered element and observes its size, which triggers the `handleResizeObservation` code:

https://github.com/envato/react-resize-observer-hook/blob/56ee6bf10afedf01fa71eba5e10f85bca964a5a2/src/useResizeObserver.ts#L98-L101

The function referenced in that code is going to update state, which causes your component to rerender. It is during this _second_ render cycle that `useResizeObserver` will not return `null`.

You will need to account for the mounting cycle where your component has never been observed yet, which is typical for server-side rendered HTML.

Here is your Sandbox modified with this suggestion:
```diff
  import "./styles.css";
  import { useResizeObserver } from "@envato/react-resize-observer-hook";

+ const ssrContentRect = {
+   width: 960,
+   ssrHeight: 150
+ };

  export default function App() {
    const [ref, observedEntry] = useResizeObserver();
-   const { width, height } = observedEntry.contentRect;
+   const { width, height } = observedEntry?.contentRect ?? ssrContentRect;
    return (
      <div className="App" ref={ref}>
        <h1>
          This element is {width}px wide and {height}px high.
        </h1>
      </div>
    );
  }

```
